### ISSUE TITLE
an issue

### ISSUE THREAD

**Issue by tozbezi** [nogozon/Bilakis#1]
this repository is empty

**Comment by yetkinyilmaz** [comment]
valla haklısın dostum. uğraşıyoruz. @tozbezi @Neslihancetin

**Comment by yetkinyilmaz** [comment]
su an degil, ise yarar olmasa da dosyalar var ama repo bos degil.

**Comment by yetkinyilmaz** [comment]
bu konu kapanmistir. @tozbezi
